const fs = require('fs');
const path = require('path');

class EmailTemplates {
    /**
     * Generate HTML for admin notification
     */
    static generateAdminNotification(data) {
        return `
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: #4CAF50; color: white; padding: 20px; text-align: center; border-radius: 5px 5px 0 0; }
                .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 5px 5px; }
                .field { margin-bottom: 15px; }
                .label { font-weight: bold; color: #555; }
                .value { color: #333; }
                .footer { margin-top: 30px; text-align: center; color: #777; font-size: 12px; }
                .button { background: #4CAF50; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>New Contact Form Submission</h1>
                </div>
                <div class="content">
                    <p>A new enquiry has been submitted through the contact form:</p>
                    
                    <div class="field">
                        <div class="label">Full Name:</div>
                        <div class="value">${data.full_name}</div>
                    </div>
                    
                    <div class="field">
                        <div class="label">Company Name:</div>
                        <div class="value">${data.company_name}</div>
                    </div>
                    
                    <div class="field">
                        <div class="label">Email:</div>
                        <div class="value">
                            <a href="mailto:${data.email}">${data.email}</a>
                        </div>
                    </div>
                    
                    <div class="field">
                        <div class="label">Country of Operation:</div>
                        <div class="value">${data.country_of_operation}</div>
                    </div>
                    
                    <div class="field">
                        <div class="label">Message:</div>
                        <div class="value">${data.message || 'No message provided'}</div>
                    </div>
                    
                    <div class="field">
                        <div class="label">Submission Date:</div>
                        <div class="value">${new Date(data.created_at).toLocaleString()}</div>
                    </div>
                    
                  
                    
                    <div style="margin-top: 30px; text-align: center;">
                        <a href="mailto:${data.email}" class="button">Reply to User</a>
                    </div>
                </div>
                <div class="footer">
                    <p>This email was automatically generated by the Contact Form System.</p>
                    <p>© ${new Date().getFullYear()} Your Company Name. All rights reserved.</p>
                </div>
            </div>
        </body>
        </html>
        `;
    }

    /**
     * Generate HTML for user confirmation
     */
    static generateUserConfirmation(data) {
        return `
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: #4CAF50; color: white; padding: 20px; text-align: center; border-radius: 5px 5px 0 0; }
                .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 5px 5px; }
                .footer { margin-top: 30px; text-align: center; color: #777; font-size: 12px; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Thank You for Contacting Us!</h1>
                </div>
                <div class="content">
                    <p>Dear ${data.full_name},</p>
                    
                    <p>Thank you for reaching out to us. We have received your enquiry and our team will get back to you within 24-48 hours.</p>
                    
                    <p><strong>Your enquiry details:</strong></p>
                    <ul>
                        <li><strong>Reference ID:</strong> ${data.contact_id}</li>
                        <li><strong>Company:</strong> ${data.company_name}</li>
                        <li><strong>Submitted:</strong> ${new Date(data.created_at).toLocaleString()}</li>
                    </ul>
                    
                    <p>If you have any urgent questions, please don't hesitate to contact us directly at <a href="mailto:${process.env.ADMIN_EMAIL}">${process.env.ADMIN_EMAIL}</a>.</p>
                    
                    <p>Best regards,<br>
                    The Support Team<br>
                    ${process.env.COMPANY_NAME || 'Your Company'}</p>
                </div>
                <div class="footer">
                    <p>This is an automated email. Please do not reply to this message.</p>
                    <p>© ${new Date().getFullYear()} Your Company Name. All rights reserved.</p>
                </div>
            </div>
        </body>
        </html>
        `;
    }

    /**
     * Get email subject
     */
    static getAdminSubject() {
        return `New Contact Form Submission - ${new Date().toLocaleDateString()}`;
    }

    static getUserSubject() {
        return `Thank You for Contacting ${process.env.COMPANY_NAME || 'Us'}`;
    }
}

module.exports = EmailTemplates;